# Generated by Django 3.0.4 on 2020-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200320_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='ProjectType',
            field=models.CharField(choices=[('Maintanace', 'Maintanace'), ('Security', 'Security'), ('Research', 'Research')], max_length=200, null=True),
        ),
    ]
