# Generated by Django 3.0.4 on 2020-03-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug',
            new_name='ProjectBug',
        ),
    ]
