# Generated by Django 3.0.4 on 2020-03-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200323_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbug',
            old_name='bug_name',
            new_name='name',
        ),
    ]
