# Generated by Django 3.0.4 on 2020-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200323_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbug',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=200, null=True),
        ),
    ]
