# Generated by Django 3.0.4 on 2020-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201012_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income', models.CharField(max_length=50, null=True)),
                ('Budget', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
