# Generated by Django 3.0.4 on 2020-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201012_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='monthly_budget',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
