# Generated by Django 3.0.4 on 2020-10-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_info_monthly_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 10, 13)),
        ),
    ]
